name: Daily Scraper
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # v3からv4へ更新
      - name: Set up Python
        uses: actions/setup-python@v5 # v4からv5へ更新
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
      - name: Run Script
        run: python scraper.py
